### ISSUE TITLE
styles/style.scss

### ISSUE THREAD

**Issue by Lead4u** [synergycp/available-now#1]
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: Path /home/scp/available-now/styles/style.css not found!

**Comment by cabloo** [comment]
Thanks for the report! Pushed a fix for this here: https://github.com/synergycp/available-now/commit/4b06350b22f011546933e2a82c34996fdc4a191a

If you `git pull origin master` to get the latest and then try the build again, it should work for you.
